//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CakeTable
    {
        public string CakeName { get; set; }
        public string Image { get; set; }
        public string IsSensitive { get; set; }
        public string Description { get; set; }
        public string Size { get; set; }
    }
}
